env:
  es6: true
  node: true
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
plugins:
  - "@typescript-eslint"
parser: "@typescript-eslint/parser"
parserOptions:
  project: tsconfig.json
